---
# All phabricator config values
- name: configure db credentials
  command: "{{ web_root }}/phabricator/bin/config set mysql.{{ item.key }} '{{ item.value }}'"
  with_dict: database_config
  changed_when: False

- name: run phabricator db migrations
  command: "{{ web_root }}/phabricator/bin/storage upgrade --force"
  changed_when: False

- name: configure base URI
  command: "{{ web_root }}/phabricator/bin/config set phabricator.base-uri '{{ protocol }}://{{ server_url }}/'"
  changed_when: False

- name: set daemon user
  command: "{{ web_root }}/phabricator/bin/config set phd.user '{{ users.daemon }}'"
  changed_when: False

- name: set vcs user
  command: "{{ web_root }}/phabricator/bin/config set diffusion.ssh-user '{{ users.vcs }}'"
  changed_when: False

- name: set http auth
  command: "{{ web_root }}/phabricator/bin/config set diffusion.allow-http-auth '{{ allow_http_auth }}'"
  changed_when: False

- name: configue pygments highlighting
  command: "{{ web_root }}/phabricator/bin/config set pygments.enabled 'true'"
  changed_when: False
