---
# tasks file for phabricator
- name: install packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: dependencies_ubuntu
  when: ansible_os_family == "Debian"

- name: install packages (RHEL)
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: dependencies_rhel
  when: ansible_os_family == "RedHat"

- name: install tools for local mysql
  include: local.yml
  when: database_config.host == "127.0.0.1"

- name: download phabricator from git repo
  git:
    repo: "{{ item.value }}"
    dest: "{{ web_root }}/{{ item.key }}"
    accept_hostkey: yes
  with_dict: repos

- name: enable phabricator in nginx
  template:
    src: phabricator.conf.j2
    dest: /etc/nginx/sites-enabled/phabricator.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: configure db credentials
  command: "{{ web_root }}/phabricator/bin/config set mysql.{{ item.key }} '{{ item.value }}'"
  with_dict: database_config

- name: run phabricator db migrations
  command: "{{ web_root }}/phabricator/bin/storage upgrade --force"
  changed_when: False

- name: start phabricator daemons
  command: "{{ web_root }}/phabricator/bin/phd start"
  changed_when: False

- name: configure base URI
  command: "{{ web_root }}/phabricator/bin/config set phabricator.base-uri '{{ protocol }}://{{ server_url }}/'"
  changed_when: False

- name: install pygments for better syntax highlighting
  pip:
    name: pygments

- name: configue pygments highlighting
  command: "{{ web_root }}/phabricator/bin/config set pygments.enabled 'true'"
  changed_when: False

- name: Creates repo directory
  file: path=/var/repo state=directory
